name: Audit pull request
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'https://deploy-preview-[[PR_NUMBER]]--[[NETLIFY_SITE]].netlify.com'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
